# MD007 - Unordered list indentation
# Контролирует отступы в ненумерованных списках.
# Устанавливает отступ для вложенных элементов списка в 4 пробела.
MD007:
  indent: 4

# MD010 - Hard tabs
# Запрещает использование табуляций (символов \t) для отступов, рекомендуется использовать пробелы.
# Исключает проверку внутри блоков кода, где табуляция может быть оправдана.
MD010:
  code_blocks: false

# MD013 - Maximum line length
MD013: false

# MD024 - No duplicate heading
MD024: false

# MD029 - Ordered list item prefix
# Настройка стиля нумерации списков
MD029: true

# MD033 - Inline HTML
# Запрещает использование сырого HTML в Markdown-документах из соображений безопасности и чистоты.
# Разрешает использовать только тег <iframe>, так как у Markdown нет встроенной альтернативы для вставки видео или интерактивного контента.
MD033:
  allowed_elements:
    - iframe

# MD036 - Emphasis used instead of a header
# Предупреждает, если для выделения заголовков используется жирный шрифт (**текст**) или курсив (*текст*) вместо настоящих заголовков (# Заголовок).
MD036: true

# MD051 - Link fragments should be valid
# Проверяет, что якорные ссылки (например, [текст](#раздел)) ведут на существующие заголовки в документе.
MD051: false