name: Yandex.Music sound metrics CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  clojure-formatting:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Setup Clojure tools
        uses: DeLaGuardo/setup-clojure@13
        with:
          cljfmt: 'latest'

      - name: Cache Clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-clojure-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure-

      - name: Check formatting
        run: cljfmt check

  clojure-linting:
    needs:
      - clojure-formatting
    runs-on: ubuntu-latest
    if: failure()

    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Setup Clojure tools
        uses: DeLaGuardo/setup-clojure@13
        with:
          cljfmt: 'latest'

      - name: Run cljfmt fix
        run: cljfmt fix

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@://github.com"
          
          git add .
          
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "style: ci auto-fix Clojure formatting with cljfmt"
            git push origin HEAD:${{ github.head_ref || github.ref_name }}
          fi

  markdown-formatting:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Run mdl for check markdown format
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.yaml

  publish-release:
    needs:
      - clojure-formatting
      - markdown-formatting

    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v6

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          draft: true
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}